=== AdmiringWorm/MASGAU/Data/games.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--simple elements-->
  <xs:element name="title" type="xs:string"/>
  <xs:element name="contributer" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="require_detection" />

  <!--attributes-->

  <xs:attribute name="environment_variable">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="allusersprofile"/>
        <xs:enumeration value="altsavepaths"/>
        <xs:enumeration value="appdata"/>
        <xs:enumeration value="drive"/>
        <xs:enumeration value="installlocation"/>
        <xs:enumeration value="localappdata"/>
        <xs:enumeration value="public"/>
        <xs:enumeration value="savedgames"/>
        <xs:enumeration value="steamuser"/>
        <xs:enumeration value="steamcommon"/>
        <xs:enumeration value="steamsourcemods"/>
        <xs:enumeration value="steamuserdata"/>
        <xs:enumeration value="userprofile"/>
        <xs:enumeration value="userdocuments"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="filename" type="xs:string"/>
  <xs:attribute name="game" type="xs:string"/>
  <xs:attribute name="key" type="xs:string"/>
  <xs:attribute name="language" type="xs:string"/>
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="override" default="no">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="yes"/>
        <xs:enumeration value="no"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="path" type="xs:string"/>
  <xs:attribute name="root">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="classes_root"/>
        <xs:enumeration value="current_user"/>
        <xs:enumeration value="current_config"/>
        <xs:enumeration value="dyn_data"/>
        <xs:enumeration value="local_machine"/>
        <xs:enumeration value="performance_data"/>
        <xs:enumeration value="users"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:attribute name="shortcut" type="xs:string"/>
  <xs:attribute name="value" type="xs:string"/>
  <xs:attribute name="windows_version">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="XP"/>
        <xs:enumeration value="Vista"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <!--attribute groups-->
  <xs:attributeGroup name="playstation_code">
    <xs:attribute name="prefix">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:length value="4"/>
          <xs:pattern value="[A-Z][A-Z][A-Z][A-Z]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="suffix">
      <xs:simpleType>
        <xs:restriction base="xs:integer" >
          <xs:pattern value="[0-9][0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  
  <xs:attributeGroup name="append_detract">
    <xs:attribute name="append" type="xs:string"/>
    <xs:attribute name="detract" type="xs:string"/>
  </xs:attributeGroup>
  
  
  <!--complex elements-->
  <xs:element name="location_registry">
    <xs:complexType>
      <xs:attribute ref="root" use="required"/>
      <xs:attribute ref="key" use="required"/>
      <xs:attribute ref="value" use="optional"/>
      <xs:attribute ref="windows_version" use="optional"/>
      <xs:attribute ref="language" use="optional"/>
      <xs:attributeGroup ref="append_detract" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_shortcut">
    <xs:complexType>
      <xs:attribute ref="shortcut" use="required"/>
      <xs:attribute ref="windows_version" use="optional"/>
      <xs:attribute ref="language" use="optional"/>
      <xs:attributeGroup ref="append_detract" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_game">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="windows_version" use="optional"/>
      <xs:attribute ref="language" use="optional"/>
      <xs:attributeGroup ref="append_detract" />
    </xs:complexType>
  </xs:element>

  <xs:element name="location_path">
    <xs:complexType>
      <xs:attribute ref="environment_variable" use="required"/>
      <xs:attribute ref="path" use="required"/>
      <xs:attribute ref="windows_version" use="optional"/>
      <xs:attribute ref="language" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="save">
    <xs:complexType>
      <xs:attribute ref="path" use="optional"/>
      <xs:attribute ref="filename" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="ignore">
    <xs:complexType>
      <xs:attribute ref="path" use="optional"/>
      <xs:attribute ref="filename" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="psp">
    <xs:complexType>
      <xs:attributeGroup ref="playstation_code" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ps1">
    <xs:complexType>
      <xs:attributeGroup ref="playstation_code" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ps2">
    <xs:complexType>
      <xs:attributeGroup ref="playstation_code" />
    </xs:complexType>
  </xs:element>

  <xs:element name="ps3">
    <xs:complexType>
      <xs:attributeGroup ref="playstation_code" />
    </xs:complexType>
  </xs:element>

  <xs:element name="virtualstore">
    <xs:complexType>
      <xs:attribute ref="override" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="identifier">
    <xs:complexType>
      <xs:attribute ref="path" use="optional"/>
      <xs:attribute ref="filename" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="game">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title" minOccurs="1" maxOccurs="1"/>
        <xs:choice>
          <xs:sequence>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
              <xs:element ref="location_registry" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_shortcut" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_game" minOccurs="1" maxOccurs="unbounded" />
              <xs:element ref="location_path" minOccurs="1" maxOccurs="unbounded" />
            </xs:choice>
            <xs:element ref="identifier" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="save" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element ref="ignore" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="virtualstore" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="require_detection" minOccurs="0" maxOccurs="1"/>
          </xs:sequence>
          <xs:element ref="psp" minOccurs="1" maxOccurs="unbounded"/>
          <xs:element ref="ps1" minOccurs="1" maxOccurs="unbounded"/>
          <xs:element ref="ps2" minOccurs="1" maxOccurs="unbounded"/>
          <xs:element ref="ps3" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:element ref="comment" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="contributer" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute ref="name" use="required"/>
    </xs:complexType>
  </xs:element>  
  
  <xs:element name="games">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="game" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
		<xs:attribute name="majorVersion" type="xs:integer" use="required"/>
		<xs:attribute name="minorVersion" type="xs:integer" use="required"/>
		<xs:attribute name="revisionVersion" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AdmiringWorm/MASGAU/Data/ps1.xml
<?xml version="1.0" encoding="utf-8" ?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	xsi:noNamespaceSchemaLocation="games.xsd"
	majorVersion="1" minorVersion="0" revisionVersion="0">
	
  <game name="ChronoCross»PS1">
	  <title>Chrono Cross</title>
	  <ps1 prefix="SLUS" suffix="01041" />
	  <ps1 prefix="SLUS" suffix="01080" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="ChronoTrigger»PS1">
	  <title>Chrono Trigger</title>
	  <ps1 prefix="SLUS" suffix="01363" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Descent»PS1">
	  <title>Descent</title>
	  <ps1 prefix="SLUS" suffix="00037" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="DescentMaximum»PS1.xml">
	  <title>Descent: Maximum</title>
	  <ps1 prefix="SLUS" suffix="00460" />
    <contributer>SanMadJack</contributer>
  </game>

    <game name="FearEffect»PS1">
      <title>Final Fantasy VIII</title>
      <ps1 prefix="SLUS" suffix="00920" />
      <ps1 prefix="SLUS" suffix="01056" />
      <ps1 prefix="SLUS" suffix="01057" />
      <ps1 prefix="SLUS" suffix="01058" />
      <contributer>SanMadJack</contributer>
    </game>

    <game name="FearEffect2»PS1">
      <title>Fear Effect 2: Retro Helix</title>
      <ps1 prefix="SLUS" suffix="01266" />
      <ps1 prefix="SLUS" suffix="01275" />
      <ps1 prefix="SLUS" suffix="01276" />
      <ps1 prefix="SLUS" suffix="01277" />
      <contributer>SanMadJack</contributer>
    </game>
    
    <game name="FinalFantasy4»PS1">
	    <title>Final Fantasy IV</title>
	    <ps1 prefix="SLUS" suffix="01360" />
      <contributer>SanMadJack</contributer>
    </game>

  <game name="FinalFantasy8»PS1">
	  <title>Final Fantasy VIII</title>
	  <ps1 prefix="SLUS" suffix="00892" />
	  <ps1 prefix="SLUS" suffix="00908" />
	  <ps1 prefix="SLUS" suffix="00909" />
	  <ps1 prefix="SLUS" suffix="00910" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="FinalFantasy9»PS1">
	  <title>Final Fantasy IX</title>
	  <ps1 prefix="SLUS" suffix="01251" />
	  <ps1 prefix="SLUS" suffix="01295" />
	  <ps1 prefix="SLUS" suffix="01296" />
	  <ps1 prefix="SLUS" suffix="01297" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="FinalFantasyTactics»PS1">
	  <title>Final Fantasy Tactics</title>
	  <ps1 prefix="SLUS" suffix="94221" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="MetalGearSolid»PS1">
	  <title>Metal Gear Solid</title>
	  <ps1 prefix="SLUS" suffix="00594" />
	  <ps1 prefix="SLUS" suffix="00776" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="MetalGearSolidVRMissions»PS1">
	  <title>Metal Gear Solid: VR Missions</title>
	  <ps1 prefix="SLUS" suffix="00957" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="ParasiteEve»PS1">
	  <title>Parasite Eve</title>
	  <ps1 prefix="SLUS" suffix="00662" />
	  <ps1 prefix="SLUS" suffix="00668" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="ParasiteEve2»PS1">
	  <title>Parasite Eve II</title>
	  <ps1 prefix="SLUS" suffix="01042" />
	  <ps1 prefix="SLUS" suffix="01055" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="SilentHill»PS1">
	  <title>Silent Hill</title>
	  <ps1 prefix="SLUS" suffix="00707" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="SoulBlade»PS1">
	  <title>Soul Blade</title>
	  <ps1 prefix="SLUS" suffix="00240" />
    <contributer>SanMadJack</contributer>
  </game>

</games>

=== AdmiringWorm/MASGAU/Data/ps3.xml
<?xml version="1.0" encoding="utf-8"?>
<games xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"	xsi:noNamespaceSchemaLocation="games.xsd"
	majorVersion="1" minorVersion="0" revisionVersion="0">
	
  <game name="AssassinsCreed»PS3">
		<title>Assassin's Creed</title>
		<ps3 prefix="BLUS" suffix="30089" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="BattlefieldBadcompany»PS3">
    <title>Battlefield: Bad Company</title>
    <ps3 prefix="BLUS" suffix="30118" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="BrutalLegend»PS3">
    <title>Brütal Legend</title>
    <ps3 prefix="BLUS" suffix="30330" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="CivilizationRevolution»PS3">
	  <title>Sid Meier's Civilization: Revolution</title>
	  <ps3 prefix="BLUS" suffix="30130" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Darkness»PS3">
	  <title>The Darkness</title>
	  <ps3 prefix="BLUS" suffix="30035" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="DeadSpace»PS3">
	  <title>Dead Space</title>
	  <ps3 prefix="BLUS" suffix="30177" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="DevilMayCry4»PS3">
	  <title>Devil May Cry 4</title>
	  <ps3 prefix="BLUS" suffix="30092" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Echochrome»PS3">
	  <title>Echochrome</title>
	  <ps3 prefix="NPUA" suffix="80134" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="ElderScrolls4Oblivion»PS3">
	  <title>Elder Scrolls IV: Oblivion</title>
	  <ps3 prefix="BLUS" suffix="30007" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Elefunk»PS3">
	  <title>Elefunk</title>
	  <ps3 prefix="NPUA" suffix="80157" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="EternalSonata»PS3">
	  <title>Eternal Sonata</title>
	  <ps3 prefix="BLUS" suffix="30161" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="FinalFantasy13»PS3">
	  <title>Final Fantasy XIII</title>
	  <ps3 prefix="MRTC" suffix="00003" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Flow»PS3">
	  <title>Flow</title>
	  <ps3 prefix="NPUA" suffix="80001" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Flower»PS3">
	  <title>Flower</title>
	  <ps3 prefix="NPUA" suffix="80083" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Folklore»PS3">
	  <title>Folklore</title>
	  <ps3 prefix="BCUS" suffix="98147" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="HeavenlySword»PS3">
	  <title>Heavenly Sword</title>
	  <ps3 prefix="BCUS" suffix="98132" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="inFamous»PS3">
	  <title>inFamous</title>
	  <ps3 prefix="BCUS" suffix="98119" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Jeopardy»PS3">
	  <title>Jeopardy!</title>
	  <ps3 prefix="NPUA" suffix="80227" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Lemmings»PS3">
    <title>Lemmings</title>
    <ps3 prefix="NPUA" suffix="80012" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="LuminesSupernova»PS3">
    <title>Lumines Supernova</title>
    <ps3 prefix="NPUB" suffix="30048" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="UltimateAlliance»PS3">
    <title>Ultimate Alliance</title>
    <ps3 prefix="BLUS" suffix="30010" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="MirrorsEdge»PS3">
	  <title>Mirror's Edge</title>
	  <ps3 prefix="BLUS" suffix="30179" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="PrinceOfPersia»PS3">
	  <title>Prince of Persia</title>
	  <ps3 prefix="BLUS" suffix="30214" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="RagDollKungFuFistsOfPlastic»PS3">
	  <title>Rag Doll Kung Fu: Fists of Plastic</title>
	  <ps3 prefix="NPUA" suffix="80217" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="RatchetClankFutureToolsOfDestruction»PS3">
	  <title>Ratchet &amp; Clank Future: Tools of Destruction</title>
	  <ps3 prefix="BCUS" suffix="98127" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="RatchetClankFutureQuestForBooty»PS3">
	  <title>Ratchet &amp; Clank Future: Quest For Booty</title>
	  <ps3 prefix="NPUA" suffix="80145" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="RedFactionGuerrilla»PS3">
	  <title>Red Faction: Guerrilla</title>
	  <ps3 prefix="BLUS" suffix="30258" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="ResidentEvil5»PS3">
	  <title>Resident Evil 5</title>
	  <ps3 prefix="BLUS" suffix="30270" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="ResistanceFallOfMan»PS3">
	  <title>Resistance: Fall of Man</title>
	  <ps3 prefix="BCUS" suffix="98107" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Resistance2»PS3">
	  <title>Resistance 2</title>
	  <ps3 prefix="BCUS" suffix="98120" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="SavageMoon»PS3">
	  <title>Savage Moon</title>
	  <ps3 prefix="NPUA" suffix="80228" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Shatter»PS3">
    <title>Shatter</title>
    <ps3 prefix="NPUB" suffix="30091" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="SilentHillHomecoming»PS3">
	  <title>Silent Hill: Homecoming</title>
	  <ps3 prefix="BLUS" suffix="30169" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="SoulCalibur4»PS3">
	  <title>Soul Calibur IV</title>
	  <ps3 prefix="BLUS" suffix="30160" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="SuperStardustHD»PS3">
	  <title>Super Stardust HD</title>
	  <ps3 prefix="NPUA" suffix="80068" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="UnchartedDrakesFortune»PS3">
	  <title>Uncharted: Drake's Fortune</title>
	  <ps3 prefix="BCUS" suffix="98103" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="UnrealTournament3»PS3">
	  <title>Unreal Tournament III</title>
	  <ps3 prefix="BLUS" suffix="30086" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="ValkyriaChronicles»PS3">
	  <title>Valkyria Chronicles</title>
	  <ps3 prefix="BLUS" suffix="30196" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="WheelOfFortune»PS3">
	  <title>Wheel of Fortune</title>
	  <ps3 prefix="NPUA" suffix="80137" />
    <contributer>SanMadJack</contributer>
  </game>

  <game name="Wolfenstein3D»PS3">
	  <title>Wolfenstein 3D</title>
	  <ps3 prefix="NPUB" suffix="30074" />
    <contributer>SanMadJack</contributer>
  </game>

</games>
